about:
  description: Nimbus Feature Manifest for Monitor Web testing
channels:
  - stage
  - production
features:
  example-feature:
    description: An example feature
    variables:
      enabled:
        description: If the feature is enabled
        type: Boolean
        default: false
      something:
        description: Another variable
        type: Option<String>
        default: null
    defaults:
      - channel: stage
        value: { "enabled": true }
      - channel: production
        value: { "something": "wicked" }

types:
  objects: {}
  enums: {}
