name: Glean probe-scraper
on:
  push:
    paths:
      - src/telemetry/frontend-metrics.yaml
      - src/telemetry/backend-metrics.yaml
  pull_request:
    paths:
      - src/telemetry/frontend-metrics.yaml
      - src/telemetry/backend-metrics.yaml
jobs:
  glean-probe-scraper:
    uses: mozilla/probe-scraper/.github/workflows/glean.yaml@main