name: Glean probe-scraper
on:
  push:
    paths:
      - src/telemetry/frontend-metrics.yml
      - src/telemetry/backend-metrics.yml
  pull_request:
    paths:
      - src/telemetry/frontend-metrics.yml
      - src/telemetry/backend-metrics.yml
jobs:
  glean-probe-scraper:
    uses: mozilla/probe-scraper/.github/workflows/glean.yaml@main