name: Lighthouse CI
on: [push]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://monitor.mozilla.org
            https://monitor.mozilla.org/breaches
            https://monitor.mozilla.org/breaches/NazApi
            https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/
            https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/breaches
            https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/breaches/NazApi
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage