name: Monitor e2e Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  monitore2e:
    name: 'Monitor Application e2e Tests'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.23.0-focal
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.x'

      - name: Install Node dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Upload html report as artifact to troubleshoot failures.
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
